Importing the useful libraries

In [22]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import csv
import pbs
#from pickle_vocab import *
#from cooc import *
import seaborn as sns

## Loading the data

In [4]:
def load_test_data(data_path):
    """Loads data and returns ids (event ids) and X (feature vector)"""
    
    f = open(data_path, encoding='utf-8')
    x = f.readlines()
    tweets = []
    ids = []
    for str in x :
        id, tweet = str.split(',',1)
        tweets.append(tweet)
        ids.append(id)

    x = pd.DataFrame(tweets,ids,columns=['Tweets'])
    
    return x

test = load_test_data('Datasets/test_data.txt')
#test.head()

In [5]:
def load_train_data(data_path):
    """Loads data and returns ids (event ids) and X (feature vector)"""
    
    f = open(data_path, encoding="utf-8")
    x = f.readlines()
    x = pd.DataFrame(x,columns=['Tweets'])
    
    return x

In [6]:
pos = load_train_data('Datasets/train_pos.txt')
pos_full = load_train_data('Datasets/train_pos_full.txt')
#pos.head()

In [7]:
neg = load_train_data('Datasets/train_neg.txt')
neg_full = load_train_data('Datasets/train_neg_full.txt')
#neg.head()

In [8]:
pos["y"]=1
pos_full["y"]=1
#pos.head()

In [9]:
neg["y"]=-1
neg_full["y"]=-1
#neg.head()

In [10]:
train = pd.concat([pos,neg])
train.reset_index(drop=True,inplace=True)
train_full = pd.concat([pos_full,neg_full])
train_full.reset_index(drop=True,inplace=True)
#train.head()

In [11]:
del train
del pos
del pos_full
del neg
del neg_full

In [214]:
print("following rows get NaN weights")
train.loc[[29049, 52357, 56151, 68379, 69973, 114433, 133011, 175789, 190542]]

following rows get NaN weights


Tweets  y
29049                            heyheyheyhey\n  1
52357              #ireland #ireland #ireland\n  1
56151                  gilipollas #everywhere\n  1
68379                  #absolutely beastingit\n  1
69973   #haveagooddaytomorrow #goodnightworld\n  1
114433                       #killingmesoftly\n -1
133011                      catss everywheree\n -1
175789                 straks nederland toets\n -1
190542                          ziekjes thuis\n -1

In [12]:
test.loc[['4590']]

Tweets
4590  #thatsjustmethough\n

In [13]:
with open('vocab.pkl','rb') as f:
    vocab = pickle.load(f)

vocab, vocab_full

NameError: name 'pickle' is not defined

In [14]:
with open('vocab_full.pkl','rb') as f:
    vocab_full = pickle.load(f)

NameError: name 'pickle' is not defined

In [15]:
max(vocab.values())

NameError: name 'vocab' is not defined

In [16]:
#!/usr/bin/env python3
import pickle


def pickle_vocab_full():
    vocab = dict()
    with open('vocab_cut_full.txt') as f:
        for idx, line in enumerate(f):
            vocab[line.strip()] = idx

    with open('vocab_full.pkl', 'wb') as f:
        pickle.dump(vocab, f, pickle.HIGHEST_PROTOCOL)
    
pickle_vocab_full()

In [17]:
#!/usr/bin/env python3
from scipy.sparse import *
import numpy as np
import pickle


def cooc_full():
    with open('vocab_full.pkl', 'rb') as f:
        vocab = pickle.load(f)
    vocab_size = len(vocab)

    data, row, col = [], [], []
    counter = 1
    for fn in ['Datasets/train_pos_full.txt', 'Datasets/train_neg_full.txt']:
        with open(fn) as f:
            for line in f:
                tokens = [vocab.get(t, -1) for t in line.strip().split()]
                tokens = [t for t in tokens if t >= 0]
                for t in tokens:
                    for t2 in tokens:
                        data.append(1)
                        row.append(t)
                        col.append(t2)

                if counter % 10000 == 0:
                    print(counter)
                counter += 1
    cooc = coo_matrix((data, (row, col)))
    print("summing duplicates (this can take a while)")
    cooc.sum_duplicates()
    with open('cooc_full.pkl', 'wb') as f:
        pickle.dump(cooc, f, pickle.HIGHEST_PROTOCOL)
        
        
cooc_full()

10000
20000
30000
40000
50000
60000
70000
80000


KeyboardInterrupt: 

In [37]:
with open('cooc.pkl','rb') as f:
    cooc = pickle.load(f)
cooc

<21160x21160 sparse matrix of type '<class 'numpy.int32'>'
	with 3184638 stored elements in COOrdinate format>

In [219]:
cooc.data

array([273434,  97020,  57576, ...,      2,      2,      8])

In [19]:
cooc.row

array([    0,     1,     2, ..., 12840, 14651, 21159])

In [221]:
cooc.col

array([    0,     0,     0, ..., 21159, 21159, 21159])

In [222]:
print(cooc)

  (0, 0)	273434
  (1, 0)	97020
  (2, 0)	57576
  (3, 0)	38886
  (4, 0)	47366
  (5, 0)	41118
  (6, 0)	41428
  (7, 0)	58492
  (8, 0)	4744
  (9, 0)	10364
  (10, 0)	31758
  (11, 0)	12300
  (12, 0)	27856
  (13, 0)	21426
  (14, 0)	22728
  (15, 0)	14316
  (16, 0)	29786
  (17, 0)	15902
  (18, 0)	20674
  (19, 0)	14742
  (20, 0)	21172
  (21, 0)	19938
  (22, 0)	8938
  (23, 0)	12654
  (24, 0)	6002
  :	:
  (208, 21159)	4
  (239, 21159)	2
  (250, 21159)	2
  (273, 21159)	2
  (314, 21159)	6
  (349, 21159)	2
  (444, 21159)	2
  (676, 21159)	2
  (693, 21159)	2
  (883, 21159)	2
  (1048, 21159)	2
  (1050, 21159)	2
  (1388, 21159)	2
  (1415, 21159)	2
  (2291, 21159)	2
  (2915, 21159)	2
  (3359, 21159)	2
  (6055, 21159)	2
  (7507, 21159)	2
  (7875, 21159)	2
  (7879, 21159)	2
  (9534, 21159)	2
  (12840, 21159)	2
  (14651, 21159)	2
  (21159, 21159)	8


In [36]:
cooc.toarray()
#cooc.style.background_gradient(cmap=coolwarm,axis=1)
pd.d
sns.heatmap(cooc)
#sns.heatmap(pd.DataFrame(cooc))

ValueError: Must pass 2-d input

In [224]:
cooc.toarray().shape

(21160, 21160)

In [16]:
#we = np.load("embeddings.npy")
we_full = np.load("embeddings_full.npy")
we_full

array([[-0.00790058, -0.00630557,  0.00753521, ..., -0.0283808 ,
         0.01144536, -0.00558127],
       [ 0.0029428 ,  0.01254714, -0.01901694, ..., -0.02141594,
         0.02366955,  0.02600938],
       [-0.00650199, -0.00820677, -0.00627628, ..., -0.02379747,
         0.00326442,  0.00680607],
       ...,
       [ 0.49645731, -1.61725388, -0.0079772 , ..., -0.25880692,
        -0.34577931,  0.70514542],
       [ 0.52614538,  0.36968974, -0.77102577, ..., -1.64859207,
         0.39028181, -2.50558299],
       [-0.32842242,  1.13262929, -1.06326081, ..., -0.60556867,
         0.75839111,  1.09999427]])

In [226]:
we.shape

(21160, 20)

In [9]:
#!/usr/bin/env python3
from scipy.sparse import *
import numpy as np
import pickle
import random



print("loading cooccurrence matrix")
with open('cooc_full.pkl', 'rb') as f:
    cooc = pickle.load(f)
print("{} nonzero entries".format(cooc.nnz))

nmax = 100
print("using nmax =", nmax, ", cooc.max() =", cooc.max())

print("initializing embeddings")
embedding_dim = 20
xs = np.random.normal(size=(cooc.shape[0], embedding_dim))
ys = np.random.normal(size=(cooc.shape[1], embedding_dim))

eta = 0.001
alpha = 3 / 4

epochs = 10

for epoch in range(epochs):
    print("epoch {}".format(epoch))
    for ix, jy, n in zip(cooc.row, cooc.col, cooc.data):
        logn = np.log(n)
        fn = min(1.0, (n / nmax) ** alpha)
        x, y = xs[ix, :], ys[jy, :]
        scale = 2 * eta * fn * (logn - np.dot(x, y))
        xs[ix, :] += scale * y
        ys[jy, :] += scale * x
np.save('embeddings_full', xs)

loading cooccurrence matrix
46596034 nonzero entries
using nmax = 100 , cooc.max() = 2599902
initializing embeddings
epoch 0
epoch 1
epoch 2
epoch 3
epoch 4
epoch 5
epoch 6
epoch 7
epoch 8
epoch 9


In [17]:
def representation(tweet, we, vocab):
    acc = np.array(0)
    n_ignored_word = 0
    for word in tweet.split():
        if word not in vocab.keys():
            n_ignored_word += 1
        else:
            try:
                acc = np.add(acc,we[vocab[word]])
            except: 
                print("problem with " + word) #last word from vocab is missing in cooc
                n_ignored_word += 1
    n = len(tweet.split()) - n_ignored_word
    acc = acc/n
    return(acc)

In [34]:
train["w"] = train["Tweets"].apply(lambda x: representation(x, we, vocab))

problem with #10factsaboutme
problem with #10factsaboutme
problem with #10factsaboutme
problem with #10factsaboutme
problem with #10factsaboutme


In [18]:
train_full["w"] = train_full["Tweets"].apply(lambda x: representation(x, we_full, vocab_full))

In [23]:
col = ["w" + str(k) for k in range(20)]
col

['w0',
 'w1',
 'w2',
 'w3',
 'w4',
 'w5',
 'w6',
 'w7',
 'w8',
 'w9',
 'w10',
 'w11',
 'w12',
 'w13',
 'w14',
 'w15',
 'w16',
 'w17',
 'w18',
 'w19']

In [22]:
train_full.drop("Tweets",axis=1,inplace=True)

KeyError: "['Tweets'] not found in axis"

In [24]:
#train.drop("Tweets",axis=1,inplace=True)
#train[col] = train["w"].apply(pd.Series)
#train.drop("w",axis=1,inplace=True)



train_full[col] = train_full["w"].apply(pd.Series)
train_full.drop("w",axis=1,inplace=True)

In [25]:
with open('train_full.pkl', 'wb') as f:
        pickle.dump(train_full, f, pickle.HIGHEST_PROTOCOL)

In [26]:
from IPython.display import display

display(train_full.head())

y        w0        w1        w2        w3        w4        w5        w6  \
0  1 -0.296790 -0.181150 -0.058083  0.322222 -0.542621 -0.024000  0.140801   
1  1 -0.202436 -0.280010 -0.107246  0.239919 -0.509784 -0.033202  0.081003   
2  1 -0.220637 -0.083819  0.100908  0.222788 -0.278018 -0.098640  0.052325   
3  1 -0.268295 -0.193417 -0.071036  0.369684 -0.534334  0.037926  0.223013   
4  1 -0.106054 -0.253317  0.099771  0.030015 -0.266051  0.050594  0.118562   

         w7        w8  ...       w10       w11       w12       w13       w14  \
0 -0.151043  0.080479  ...  0.065230  0.089998 -0.074064  0.487775 -0.113918   
1 -0.129831  0.085327  ...  0.118092  0.126240  0.022105  0.426787 -0.094366   
2 -0.099279 -0.011704  ...  0.044298  0.069571 -0.029328  0.195117  0.058874   
3 -0.237248 -0.027922  ...  0.064163  0.087668 -0.104771  0.604485 -0.082731   
4 -0.103226  0.025749  ...  0.090308  0.148502 -0.104850  0.293243 -0.184430   

        w15       w16       w17       w18       w19  
0  0.182005  0.249724 -0.118905  0.098660  0.156168  
1  0.178490  0.300231 -0.039059  0.122455  0.086746  
2  0.114208  0.135762 -0.115157  0.062747  0.111751  
3  0.160737  0.253678 -0.089962  0.072788  0.119213  
4  0.301689  0.187145 -0.092530 -0.059525  0.197912  

[5 rows x 21 columns]

In [232]:
test.head()

Tweets
1  sea doo pro sea scooter ( sports with the port...
2  <user> shucks well i work all week so now i ca...
3          i cant stay away from bug thats my baby\n
4  <user> no ma'am ! ! ! lol im perfectly fine an...
5  whenever i fall asleep watching the tv , i alw...

In [27]:
test["w"] = test["Tweets"].apply(lambda x: representation(x, we_full, vocab_full))
test[col] = test["w"].apply(pd.Series)
test.drop("w",axis=1,inplace=True)
test.drop("Tweets",axis=1,inplace=True)

In [234]:
test

w0        w1        w2        w3        w4        w5        w6  \
1      0.259533  0.059221 -0.450866 -0.689856  0.480041 -0.267784  0.051785   
2      0.150485 -0.073187 -0.203847 -0.686830  0.483774 -0.184477  0.248559   
3      0.109122 -0.055159 -0.075084 -0.602511  0.323006 -0.402221  0.205848   
4      0.200103  0.153898 -0.171113 -0.550022  0.206411 -0.279831  0.057420   
5      0.271728 -0.070988 -0.006069 -0.511087  0.414814 -0.379588  0.132693   
6      0.177140 -0.064049 -0.235508 -0.671921  0.468047 -0.351670  0.123075   
7      0.050540  0.023630 -0.318031 -0.700890  0.656585 -0.121047  0.151539   
8      0.079734 -0.147615 -0.081583 -0.771016  0.457424 -0.368448  0.115835   
9      0.069434 -0.049755 -0.068777 -0.770877  0.539732 -0.381339  0.183634   
10     0.088795 -0.036685 -0.089279 -0.693793  0.477863 -0.204369  0.208715   
11     0.287058 -0.138410  0.010715 -0.479806  0.316029 -0.484841  0.014957   
12     0.066614  0.008910  0.109345 -0.640204  0.493406 -0.374340  0.129307   
13     0.054412  0.106687 -0.119148 -0.742847  0.286058 -0.466376  0.117011   
14     0.163163 -0.021450 -0.172914 -0.577753  0.406328 -0.321955  0.224336   
15     0.137139 -0.121667 -0.123387 -0.709934  0.471520 -0.292488  0.219513   
16     0.063949 -0.135759 -0.096592 -0.678698  0.489010 -0.346265  0.187516   
17    -0.017614  0.034036  0.047901 -0.370944  0.215342 -0.385670 -0.121219   
18     0.117683 -0.061740 -0.162927 -0.675919  0.441804 -0.292113  0.269865   
19     0.047242 -0.103232 -0.091494 -0.697225  0.475630 -0.349232  0.227422   
20     0.021766 -0.413402 -0.037518 -0.625994  0.324803 -0.195039 -0.097629   
21     0.049045 -0.005469  0.032893 -0.459132  0.508543 -0.255998  0.074070   
22    -0.070942 -0.029376 -0.024939 -0.522467  0.305051  0.062346 -0.166466   
23     0.023649 -0.044820 -0.136533 -0.619034  0.597789 -0.405749  0.303869   
24     0.274662  0.018599 -0.154841 -0.408611  0.234922 -0.183656  0.271233   
25     0.011366  0.015348 -0.037457 -0.509686  0.483141 -0.234191  0.177655   
26     0.362176 -0.224930  0.100445 -0.611514  0.120449 -0.484616  0.247347   
27    -0.108318 -0.281613 -0.100746 -0.695718  0.446815 -0.449424  0.094348   
28     0.084650 -0.106256 -0.096105 -0.601734  0.439750 -0.233057  0.161708   
29     0.224903 -0.106390 -0.250410 -0.521524  0.174684 -0.083515  0.150899   
30     0.064165 -0.043637 -0.039208 -0.753284  0.418657 -0.208076  0.206161   
...         ...       ...       ...       ...       ...       ...       ...   
9971   0.136756 -0.002900 -0.263377 -0.735713  0.502383 -0.299195  0.040730   
9972   0.136756 -0.002900 -0.263377 -0.735713  0.502383 -0.299195  0.040730   
9973   0.050440  0.025633 -0.114196 -0.792517  0.505306 -0.414891  0.224813   
9974   0.208188 -0.126444 -0.007375 -0.662876  0.461378 -0.097293  0.236183   
9975   0.402635 -0.051592 -0.138177 -0.542206  0.606092 -0.257537 -0.000612   
9976  -0.182998  0.146484 -0.305557 -0.457726  0.345524 -0.506654 -0.026890   
9977  -0.182998  0.146484 -0.305557 -0.457726  0.345524 -0.506654 -0.026890   
9978   0.231747 -0.431065 -0.077025 -0.174410  0.064054 -0.416887  0.255599   
9979   0.146350 -0.072675 -0.113447 -0.710326  0.516614 -0.411723  0.221823   
9980   0.143659 -0.404978 -0.117172 -0.529023  0.190122 -0.065609  0.254803   
9981   0.016662  0.040276 -0.091439 -0.785693  0.590227 -0.287410  0.218790   
9982  -0.225963 -0.067056 -0.052156 -0.825591  0.371571 -0.196164  0.209115   
9983   0.108350 -0.047128 -0.097876 -0.744953  0.493168 -0.368248  0.224852   
9984   0.186735 -0.006388 -0.048265 -0.796490  0.431606 -0.317504  0.249203   
9985   0.122909 -0.047438 -0.081060 -0.605318  0.472083 -0.048722  0.356006   
9986   0.122909 -0.047438 -0.081060 -0.605318  0.472083 -0.048722  0.356006   
9987   0.194888  0.043920  0.300667 -0.649810  0.234482 -0.154453 -0.029021   
9988   0.083167 -0.038568 -0.159210 -0.663637  0.515697 -0.339087  0.198127   
9989   0.125390  0.042054 -0.109052 -0.641847  0.340131 -0.2442

In [28]:
train_full[train_full.isnull().any(axis=1)].index

Int64Index([  29049,   56151,   68379,  114187,  152738,  214353,  224611,
             240835,  248364,  262903,  273027,  395411,  423819,  429381,
             445207,  522076,  541049,  601783,  655092,  672119,  688454,
             772457,  788210,  800748,  805714,  816453,  900218,  909214,
             920188,  994920, 1023925, 1026478, 1033297, 1039583, 1054132,
            1072735, 1105838, 1116982, 1116983, 1140450, 1147351, 1199854,
            1233454, 1264433, 1283011, 1366486, 1440168, 1553488, 1562646,
            1594451, 1614181, 1621006, 1646450, 1660651, 1716033, 1757957,
            1782742, 1809894, 1827675, 1840472, 1869113, 1945025, 2013870,
            2022990, 2071721, 2082029, 2089452, 2100361, 2130263, 2140897,
            2151061, 2167952, 2177220, 2303468, 2349139, 2386666, 2403651,
            2442445, 2467230],
           dtype='int64')

In [29]:
train_full.dropna(inplace=True)

In [30]:
test[test.isnull().any(axis=1)].index

Index(['4590'], dtype='object')

In [31]:
test.dropna(inplace=True)

In [32]:
X = train_full.drop("y", axis=1)
y = train_full["y"]

In [33]:
from sklearn.linear_model import SGDClassifier

clf = SGDClassifier()
clf.fit(X, y) 
test["p"]=clf.predict(test)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  FutureWarning)


You should first create a folder named **Submissions**

In [36]:
test["p"].to_csv("Submissions/submission_full.csv",header=False)

## Data Analysis

## Word enbeddings matrix

### Generation

### Visualization

## Building the text classifier

### Training texts features

### Linear classifiers

### Predictions

## Output creation and visualization

### Creating the submission file

### Visualization of the results