Importing the useful libraries

In [206]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import csv
import pbs
from pickle_vocab import *
from cooc import *

## Loading the data

In [207]:
def load_test_data(data_path):
    """Loads data and returns ids (event ids) and X (feature vector)"""
    
    f = open(data_path)
    x = f.readlines()
    tweets = []
    ids = []
    for str in x :
        id, tweet = str.split(',',1)
        tweets.append(tweet)
        ids.append(id)

    x = pd.DataFrame(tweets,ids,columns=['Tweets'])
    
    return x

test = load_test_data('Datasets/test_data.txt')
test.head()

Tweets
1  sea doo pro sea scooter ( sports with the port...
2  <user> shucks well i work all week so now i ca...
3          i cant stay away from bug thats my baby\n
4  <user> no ma'am ! ! ! lol im perfectly fine an...
5  whenever i fall asleep watching the tv , i alw...

In [208]:
def load_train_data(data_path):
    """Loads data and returns ids (event ids) and X (feature vector)"""
    
    f = open(data_path)
    x = f.readlines()
    x = pd.DataFrame(x,columns=['Tweets'])
    
    return x

In [209]:
pos = load_train_data('Datasets/train_pos.txt')
pos.head()

Tweets
0  <user> i dunno justin read my mention or not ....
1  because your logic is so dumb , i won't even c...
2  " <user> just put casper in a box ! " looved t...
3  <user> <user> thanks sir > > don't trip lil ma...
4  visiting my brother tmr is the bestest birthda...

In [210]:
neg = load_train_data('Datasets/train_neg.txt')
neg.head()

Tweets
0  vinco tresorpack 6 ( difficulty 10 of 10 objec...
1  glad i dot have taks tomorrow ! ! #thankful #s...
2  1-3 vs celtics in the regular season = were fu...
3  <user> i could actually kill that girl i'm so ...
4  <user> <user> <user> i find that very hard to ...

In [211]:
pos["y"]=1
pos.head()

Tweets  y
0  <user> i dunno justin read my mention or not ....  1
1  because your logic is so dumb , i won't even c...  1
2  " <user> just put casper in a box ! " looved t...  1
3  <user> <user> thanks sir > > don't trip lil ma...  1
4  visiting my brother tmr is the bestest birthda...  1

In [212]:
neg["y"]=-1
neg.head()

Tweets  y
0  vinco tresorpack 6 ( difficulty 10 of 10 objec... -1
1  glad i dot have taks tomorrow ! ! #thankful #s... -1
2  1-3 vs celtics in the regular season = were fu... -1
3  <user> i could actually kill that girl i'm so ... -1
4  <user> <user> <user> i find that very hard to ... -1

In [213]:
train = pd.concat([pos,neg])
train.reset_index(drop=True,inplace=True)
train.head()

Tweets  y
0  <user> i dunno justin read my mention or not ....  1
1  because your logic is so dumb , i won't even c...  1
2  " <user> just put casper in a box ! " looved t...  1
3  <user> <user> thanks sir > > don't trip lil ma...  1
4  visiting my brother tmr is the bestest birthda...  1

In [214]:
print("following rows get NaN weights")
train.loc[[29049, 52357, 56151, 68379, 69973, 114433, 133011, 175789, 190542]]

following rows get NaN weights


Tweets  y
29049                            heyheyheyhey\n  1
52357              #ireland #ireland #ireland\n  1
56151                  gilipollas #everywhere\n  1
68379                  #absolutely beastingit\n  1
69973   #haveagooddaytomorrow #goodnightworld\n  1
114433                       #killingmesoftly\n -1
133011                      catss everywheree\n -1
175789                 straks nederland toets\n -1
190542                          ziekjes thuis\n -1

In [215]:
test.loc[['4590']]

Tweets
4590  #thatsjustmethough\n

In [216]:
with open('vocab.pkl','rb') as f:
    vocab = pickle.load(f)
vocab

{'<user>': 0,
 '!': 1,
 'i': 2,
 'the': 3,
 '.': 4,
 ',': 5,
 'to': 6,
 'you': 7,
 '(': 8,
 '<url>': 9,
 'a': 10,
 '...': 11,
 'and': 12,
 'my': 13,
 'me': 14,
 'of': 15,
 '?': 16,
 'is': 17,
 'for': 18,
 'in': 19,
 'it': 20,
 '"': 21,
 'this': 22,
 'so': 23,
 '-': 24,
 'with': 25,
 'on': 26,
 'that': 27,
 ')': 28,
 'be': 29,
 "i'm": 30,
 'have': 31,
 ':': 32,
 'but': 33,
 'just': 34,
 'rt': 35,
 'love': 36,
 'your': 37,
 'all': 38,
 'not': 39,
 'was': 40,
 'at': 41,
 'are': 42,
 '..': 43,
 'like': 44,
 '/': 45,
 'get': 46,
 'up': 47,
 'frame': 48,
 '&': 49,
 'lol': 50,
 'know': 51,
 'good': 52,
 'do': 53,
 'u': 54,
 'now': 55,
 'when': 56,
 'one': 57,
 'if': 58,
 'we': 59,
 'follow': 60,
 'no': 61,
 'can': 62,
 'what': 63,
 'go': 64,
 "don't": 65,
 'out': 66,
 'x': 67,
 'will': 68,
 'day': 69,
 "'": 70,
 'please': 71,
 'from': 72,
 'see': 73,
 'too': 74,
 'want': 75,
 'there': 76,
 'back': 77,
 "it's": 78,
 'today': 79,
 'about': 80,
 'really': 81,
 'how': 82,
 'got': 83,
 'thanks': 8

In [217]:
max(vocab.values())

21160

In [8]:
#!/usr/bin/env python3
from scipy.sparse import *
import numpy as np
import pickle


def cooc_full():
    with open('vocab_full.pkl', 'rb') as f:
        vocab = pickle.load(f)
    vocab_size = len(vocab)

    data, row, col = [], [], []
    counter = 1
    for fn in ['Datasets/train_pos_full.txt', 'Datasets/train_neg_full.txt']:
        with open(fn) as f:
            for line in f:
                tokens = [vocab.get(t, -1) for t in line.strip().split()]
                tokens = [t for t in tokens if t >= 0]
                for t in tokens:
                    for t2 in tokens:
                        data.append(1)
                        row.append(t)
                        col.append(t2)

                if counter % 10000 == 0:
                    print(counter)
                counter += 1
    cooc = coo_matrix((data, (row, col)))
    print("summing duplicates (this can take a while)")
    cooc.sum_duplicates()
    with open('cooc_full.pkl', 'wb') as f:
        pickle.dump(cooc, f, pickle.HIGHEST_PROTOCOL)
        
        
cooc_full = cooc_full()

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)

In [218]:
with open('cooc.pkl','rb') as f:
    cooc = pickle.load(f)
cooc

<21160x21160 sparse matrix of type '<class 'numpy.int32'>'
	with 3184638 stored elements in COOrdinate format>

In [219]:
cooc.data

array([273434,  97020,  57576, ...,      2,      2,      8])

In [220]:
cooc.row

array([    0,     1,     2, ..., 12840, 14651, 21159])

In [221]:
cooc.col

array([    0,     0,     0, ..., 21159, 21159, 21159])

In [222]:
print(cooc)

  (0, 0)	273434
  (1, 0)	97020
  (2, 0)	57576
  (3, 0)	38886
  (4, 0)	47366
  (5, 0)	41118
  (6, 0)	41428
  (7, 0)	58492
  (8, 0)	4744
  (9, 0)	10364
  (10, 0)	31758
  (11, 0)	12300
  (12, 0)	27856
  (13, 0)	21426
  (14, 0)	22728
  (15, 0)	14316
  (16, 0)	29786
  (17, 0)	15902
  (18, 0)	20674
  (19, 0)	14742
  (20, 0)	21172
  (21, 0)	19938
  (22, 0)	8938
  (23, 0)	12654
  (24, 0)	6002
  :	:
  (208, 21159)	4
  (239, 21159)	2
  (250, 21159)	2
  (273, 21159)	2
  (314, 21159)	6
  (349, 21159)	2
  (444, 21159)	2
  (676, 21159)	2
  (693, 21159)	2
  (883, 21159)	2
  (1048, 21159)	2
  (1050, 21159)	2
  (1388, 21159)	2
  (1415, 21159)	2
  (2291, 21159)	2
  (2915, 21159)	2
  (3359, 21159)	2
  (6055, 21159)	2
  (7507, 21159)	2
  (7875, 21159)	2
  (7879, 21159)	2
  (9534, 21159)	2
  (12840, 21159)	2
  (14651, 21159)	2
  (21159, 21159)	8


In [223]:
cooc.toarray()

array([[273434,  97020,  57576, ...,      0,     10,      4],
       [ 97020, 255078,  47124, ...,      0,      2,      0],
       [ 57576,  47124, 110506, ...,      0,      0,      4],
       ...,
       [     0,      0,      0, ...,      0,      0,      0],
       [    10,      2,      0, ...,      0,     10,      0],
       [     4,      0,      4, ...,      0,      0,      8]])

In [224]:
cooc.toarray().shape

(21160, 21160)

In [225]:
we = np.load("embeddings.npy")
we

array([[ 0.08293404,  0.01490157,  0.00622929, ..., -0.16190348,
        -0.1846269 , -0.18189624],
       [ 0.12380148, -0.0421271 , -0.01440238, ..., -0.30058427,
        -0.22970339, -0.25452988],
       [ 0.09969781,  0.00634767, -0.05967447, ..., -0.30113178,
        -0.29646062, -0.36644036],
       ...,
       [-0.03857365, -2.05255734, -0.04303483, ..., -0.78177959,
         0.37153678, -0.62341192],
       [ 2.09123134, -1.04694662, -0.92195585, ...,  0.26456563,
         0.18419511, -0.29720033],
       [ 1.03783875, -0.6643759 , -0.19507841, ...,  0.31626424,
        -3.13279291,  1.45051465]])

In [226]:
we.shape

(21160, 20)

In [227]:
def representation(tweet):
    acc = np.array(0)
    n_ignored_word = 0
    for word in tweet.split():
        if word not in vocab.keys():
            n_ignored_word += 1
        else:
            try:
                acc = np.add(acc,we[vocab[word]])
            except: 
                print("problem with " + word) #last word from vocab is missing in cooc
                n_ignored_word += 1
    n = len(tweet.split()) - n_ignored_word
    acc = acc/n
    return(acc)

In [228]:
train["w"] = train["Tweets"].apply(lambda x: representation(x))

problem with #10factsaboutme
problem with #10factsaboutme
problem with #10factsaboutme
problem with #10factsaboutme
problem with #10factsaboutme


In [229]:
col = ["w" + str(k) for k in range(20)]
col

['w0',
 'w1',
 'w2',
 'w3',
 'w4',
 'w5',
 'w6',
 'w7',
 'w8',
 'w9',
 'w10',
 'w11',
 'w12',
 'w13',
 'w14',
 'w15',
 'w16',
 'w17',
 'w18',
 'w19']

In [230]:
train[col] = train["w"].apply(pd.Series)
train.drop("w",axis=1,inplace=True)
train.drop("Tweets",axis=1,inplace=True)

In [231]:
train

y        w0        w1        w2        w3        w4        w5  \
0       1  0.193815  0.038084  0.040004 -0.668191  0.548065 -0.373069   
1       1  0.164580 -0.173796  0.008294 -0.758810  0.600187 -0.400949   
2       1  0.174736 -0.009662 -0.141506 -0.549435  0.538021 -0.390385   
3       1 -0.053728 -0.128535  0.083332 -0.790976  0.578776 -0.068607   
4       1 -0.000336 -0.311349  0.063379 -0.652141  0.242091 -0.023745   
5       1  0.026594 -0.006907 -0.100526 -0.749362  0.524098 -0.346801   
6       1  0.090643 -0.048549 -0.010043 -0.657629  0.385867 -0.272697   
7       1  0.105990  0.324250 -0.020413 -0.368366  0.482513 -0.298971   
8       1  0.057533 -0.066158  0.033396 -0.654281  0.382003 -0.349268   
9       1  0.195404  0.123427 -0.582616 -0.908895  0.608877 -0.441935   
10      1  0.129137  0.038000 -0.448802 -0.497718  0.416824 -0.249621   
11      1  0.152342 -0.090838 -0.065272 -0.797130  0.397763 -0.319797   
12      1  0.115335 -0.234238  0.169084 -0.797159  0.585183 -0.370648   
13      1  0.098685 -0.389735 -0.019955 -0.678899  0.277801 -0.174052   
14      1  1.191880  0.617583 -0.462429 -0.098580  0.296061 -0.395778   
15      1  0.023225 -0.021071 -0.273270 -0.664207  0.567234 -0.386798   
16      1  0.000541 -0.038776 -0.042648 -0.723572  0.683665 -0.293827   
17      1  0.098510  0.025108  0.039426 -0.698241  0.434042 -0.215793   
18      1 -0.092528 -0.483540 -0.519336 -0.382029  0.246108 -0.537233   
19      1  0.148368 -0.029490 -0.047455 -0.636341  0.206482 -0.369918   
20      1  0.014621 -0.168985  0.154581 -0.653395  0.603680 -0.058676   
21      1  0.195371  0.041933 -0.341260 -0.683975  0.462322 -0.326738   
22      1 -0.647926  0.382794 -0.364382 -0.350080  0.405311 -0.198642   
23      1  0.431344  0.234352 -0.223933 -0.467470  0.542330 -0.493254   
24      1  0.086084 -0.001272 -0.282728 -0.744964  0.423554 -0.430285   
25      1  0.319800 -0.125488  0.140683 -0.768397  0.489644 -0.392354   
26      1  0.089172  0.003057 -0.083562 -0.713030  0.561848 -0.370537   
27      1  0.155806 -0.181912 -0.027692 -0.687364  0.609148 -0.352919   
28      1  0.076135 -0.021298 -0.116054 -0.734751  0.468114 -0.387538   
29      1  0.151534 -0.099642  0.209358 -0.437885  0.590995 -0.290001   
...    ..       ...       ...       ...       ...       ...       ...   
199970 -1  0.055731 -0.012241 -0.130486 -0.746459  0.450498 -0.346154   
199971 -1  0.297843  0.163213 -0.012293 -0.642647  0.240586 -0.309025   
199972 -1 -0.233780  0.068955  0.018680 -0.586155  0.329834 -0.296460   
199973 -1 -0.021589 -0.096582 -0.328845 -0.526924  0.529845 -0.154723   
199974 -1 -0.008387  0.058342 -0.271291 -0.568739  0.412054 -0.437502   
199975 -1  0.112276 -0.080452 -0.074144 -0.686017  0.550270 -0.298152   
199976 -1  0.179296 -0.174843  0.017803 -0.632279  0.173087 -0.241606   
199977 -1  0.165669 -0.127382 -0.278162 -0.524088  0.431358 -0.475334   
199978 -1 -0.036724  0.217628 -0.141478 -0.448154  0.410855 -0.418109   
199979 -1  0.207972 -0.105136  0.031880 -0.458001  0.244160 -0.367052   
199980 -1  0.189372 -0.039800 -0.073497 -0.556647  0.255880 -0.350127   
199981 -1  0.189372 -0.039800 -0.073497 -0.556647  0.255880 -0.350127   
199982 -1  0.102016 -0.197820 -0.128734 -0.794158  0.451649 -0.335597   
199983 -1  0.125735 -0.151627 -0.130423 -0.450502  0.024635 -0.097162   
199984 -1  0.202421  0.054355 -0.162131 -0.811703  0.206355 -0.440123   
199985 -1 -0.189414 -0.107703  0.065115 -0.404680  0.370297 -0.206308   
199986 -1 -0.025078 -0.262919 -0.257395 -0.775193  0.497741 -0.282144   
199987 -1  0.052543  0.045402 -0.124361 -0.848272  0.521963 -0.375514   
199988 -1  0.055144 -0.011780 -0.061781 -0.709176  0.358456 -0.138543   
199989 -1 -0.052167 -0.144936 -0.081010 -0.653172  0.455676 -0.189837   
199990 -1  0.097675  0.159372 -0.093776 -0.644472  0.595283 -0.471159   
199991 -1  0.076217  0.092614 -0.139124 -0.581465  0.573297 -0.254949   
199992 -1  0.016207 -0.018347 -0.109245 -0.718542  0.578565 -0.479

In [232]:
test.head()

Tweets
1  sea doo pro sea scooter ( sports with the port...
2  <user> shucks well i work all week so now i ca...
3          i cant stay away from bug thats my baby\n
4  <user> no ma'am ! ! ! lol im perfectly fine an...
5  whenever i fall asleep watching the tv , i alw...

In [233]:
test["w"] = test["Tweets"].apply(lambda x: representation(x))
test[col] = test["w"].apply(pd.Series)
test.drop("w",axis=1,inplace=True)
test.drop("Tweets",axis=1,inplace=True)

problem with #10factsaboutme


In [234]:
test

w0        w1        w2        w3        w4        w5        w6  \
1      0.259533  0.059221 -0.450866 -0.689856  0.480041 -0.267784  0.051785   
2      0.150485 -0.073187 -0.203847 -0.686830  0.483774 -0.184477  0.248559   
3      0.109122 -0.055159 -0.075084 -0.602511  0.323006 -0.402221  0.205848   
4      0.200103  0.153898 -0.171113 -0.550022  0.206411 -0.279831  0.057420   
5      0.271728 -0.070988 -0.006069 -0.511087  0.414814 -0.379588  0.132693   
6      0.177140 -0.064049 -0.235508 -0.671921  0.468047 -0.351670  0.123075   
7      0.050540  0.023630 -0.318031 -0.700890  0.656585 -0.121047  0.151539   
8      0.079734 -0.147615 -0.081583 -0.771016  0.457424 -0.368448  0.115835   
9      0.069434 -0.049755 -0.068777 -0.770877  0.539732 -0.381339  0.183634   
10     0.088795 -0.036685 -0.089279 -0.693793  0.477863 -0.204369  0.208715   
11     0.287058 -0.138410  0.010715 -0.479806  0.316029 -0.484841  0.014957   
12     0.066614  0.008910  0.109345 -0.640204  0.493406 -0.374340  0.129307   
13     0.054412  0.106687 -0.119148 -0.742847  0.286058 -0.466376  0.117011   
14     0.163163 -0.021450 -0.172914 -0.577753  0.406328 -0.321955  0.224336   
15     0.137139 -0.121667 -0.123387 -0.709934  0.471520 -0.292488  0.219513   
16     0.063949 -0.135759 -0.096592 -0.678698  0.489010 -0.346265  0.187516   
17    -0.017614  0.034036  0.047901 -0.370944  0.215342 -0.385670 -0.121219   
18     0.117683 -0.061740 -0.162927 -0.675919  0.441804 -0.292113  0.269865   
19     0.047242 -0.103232 -0.091494 -0.697225  0.475630 -0.349232  0.227422   
20     0.021766 -0.413402 -0.037518 -0.625994  0.324803 -0.195039 -0.097629   
21     0.049045 -0.005469  0.032893 -0.459132  0.508543 -0.255998  0.074070   
22    -0.070942 -0.029376 -0.024939 -0.522467  0.305051  0.062346 -0.166466   
23     0.023649 -0.044820 -0.136533 -0.619034  0.597789 -0.405749  0.303869   
24     0.274662  0.018599 -0.154841 -0.408611  0.234922 -0.183656  0.271233   
25     0.011366  0.015348 -0.037457 -0.509686  0.483141 -0.234191  0.177655   
26     0.362176 -0.224930  0.100445 -0.611514  0.120449 -0.484616  0.247347   
27    -0.108318 -0.281613 -0.100746 -0.695718  0.446815 -0.449424  0.094348   
28     0.084650 -0.106256 -0.096105 -0.601734  0.439750 -0.233057  0.161708   
29     0.224903 -0.106390 -0.250410 -0.521524  0.174684 -0.083515  0.150899   
30     0.064165 -0.043637 -0.039208 -0.753284  0.418657 -0.208076  0.206161   
...         ...       ...       ...       ...       ...       ...       ...   
9971   0.136756 -0.002900 -0.263377 -0.735713  0.502383 -0.299195  0.040730   
9972   0.136756 -0.002900 -0.263377 -0.735713  0.502383 -0.299195  0.040730   
9973   0.050440  0.025633 -0.114196 -0.792517  0.505306 -0.414891  0.224813   
9974   0.208188 -0.126444 -0.007375 -0.662876  0.461378 -0.097293  0.236183   
9975   0.402635 -0.051592 -0.138177 -0.542206  0.606092 -0.257537 -0.000612   
9976  -0.182998  0.146484 -0.305557 -0.457726  0.345524 -0.506654 -0.026890   
9977  -0.182998  0.146484 -0.305557 -0.457726  0.345524 -0.506654 -0.026890   
9978   0.231747 -0.431065 -0.077025 -0.174410  0.064054 -0.416887  0.255599   
9979   0.146350 -0.072675 -0.113447 -0.710326  0.516614 -0.411723  0.221823   
9980   0.143659 -0.404978 -0.117172 -0.529023  0.190122 -0.065609  0.254803   
9981   0.016662  0.040276 -0.091439 -0.785693  0.590227 -0.287410  0.218790   
9982  -0.225963 -0.067056 -0.052156 -0.825591  0.371571 -0.196164  0.209115   
9983   0.108350 -0.047128 -0.097876 -0.744953  0.493168 -0.368248  0.224852   
9984   0.186735 -0.006388 -0.048265 -0.796490  0.431606 -0.317504  0.249203   
9985   0.122909 -0.047438 -0.081060 -0.605318  0.472083 -0.048722  0.356006   
9986   0.122909 -0.047438 -0.081060 -0.605318  0.472083 -0.048722  0.356006   
9987   0.194888  0.043920  0.300667 -0.649810  0.234482 -0.154453 -0.029021   
9988   0.083167 -0.038568 -0.159210 -0.663637  0.515697 -0.339087  0.198127   
9989   0.125390  0.042054 -0.109052 -0.641847  0.340131 -0.2442

In [235]:
train[train.isnull().any(axis=1)].index

Int64Index([29049, 52357, 56151, 68379, 69973, 114433, 133011, 175789, 190542], dtype='int64')

In [236]:
train.dropna(inplace=True)

In [237]:
test[test.isnull().any(axis=1)].index

Index(['4590'], dtype='object')

In [238]:
test.dropna(inplace=True)

In [239]:
X = train.drop("y", axis=1)
y = train["y"]

In [240]:
from sklearn.linear_model import SGDClassifier

clf = SGDClassifier()
clf.fit(X, y) 
test["p"]=clf.predict(test)

You should first create a folder named **Submissions**

In [ ]:
test["p"].to_csv("Submissions/submission.csv",header=False)

## Data Analysis

## Word enbeddings matrix

### Generation

### Visualization

## Building the text classifier

### Training texts features

### Linear classifiers

### Predictions

## Output creation and visualization

### Creating the submission file

### Visualization of the results